# index-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-index
spec:
  capacity:
    storage: 5Gi  # 용량: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # 모든 데이터 플레인들이 읽고 쓸 수 있음.
  persistentVolumeReclaimPolicy: Retain  # EFS의 file system id와 연결하므로 Retain 정책 설정
  storageClassName: efs-sc  # storageclass.yaml file에서 정의
  csi:
    driver: efs.csi.aws.com  # efs-csi-driver 설치
    volumeHandle: fs-09c306a3e1c0baea2  # file system ID
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-index
  namespace: backend  # 네임스페이스 추가
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi   
---
# sign-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sign
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-09c306a3e1c0baea2
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sign
  namespace: backend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

---
# login-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-login
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-09c306a3e1c0baea2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-login
  namespace: backend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
